// Tests for Rust Cargo.lock parser
package io.dyuti.osvplugin.parser

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class CargoParserTest {
    private val parser = CargoParser()

    @Test
    fun `canHandle returns true for Cargo-dot-lock`() {
        assertTrue(parser.canHandle("/project/Cargo.lock"))
    }

    @Test
    fun `parse cargo lock with multiple packages`() {
        val content =
            """
            [[package]]
            name = "serde"
            version = "1.0.190"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "..."

            [[package]]
            name = "tokio"
            version = "1.34.0"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "..."
            """.trimIndent()

        val deps = parser.parse("Cargo.lock", content)
        assertEquals(2, deps.size)

        val serde = deps[0]
        assertEquals("serde", serde.name)
        assertEquals("1.0.190", serde.version)
        assertEquals("crates.io", serde.ecosystem)

        val tokio = deps[1]
        assertEquals("tokio", tokio.name)
        assertEquals("1.34.0", tokio.version)
    }

    @Test
    fun `parse cargo lock ignores non-package lines`() {
        val content =
            """
            # This file is automatically generated by Cargo
            [[package]]
            name = "libc"
            version = "0.2.150"
            """.trimIndent()

        val deps = parser.parse("Cargo.lock", content)
        assertEquals(1, deps.size)
        assertEquals("libc", deps[0].name)
    }
}
