// Tests for Dart pubspec.lock parser
package io.dyuti.osvplugin.parser

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class PubspecParserTest {
    private val parser = PubspecParser()

    @Test
    fun `canHandle returns true for pubspec-dot-lock`() {
        assertTrue(parser.canHandle("/project/pubspec.lock"))
    }

    @Test
    fun `parse pubspec lock with direct and transitive`() {
        val content =
            """
# Generated by pub
packages:
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.11.0"
  collection:
    dependency: direct main
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.18.0"
  dev_test:
    dependency: direct dev
    description:
      name: dev_test
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.16.1"
            """.trimIndent()

        val deps = parser.parse("pubspec.lock", content)
        assertEquals(3, deps.size)

        val async = deps[0]
        assertEquals("async", async.name)
        assertEquals("2.11.0", async.version)
        assertEquals(true, async.transitive)
        assertEquals("runtime", async.scope)

        val collection = deps[1]
        assertEquals("collection", collection.name)
        assertEquals("1.18.0", collection.version)
        assertEquals(false, collection.transitive)

        val devTest = deps[2]
        assertEquals("dev_test", devTest.name)
        assertEquals("test", devTest.scope)
    }
}
