// Unit tests for AiScanner
package io.dyuti.osvplugin.aibom

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class AiScannerTest {
    private fun createScanner(): AiScanner = AiScanner(project = null)

    @Test
    fun `detects OpenAI API`() {
        val code = "import openai; openai.api_key = 'sk-test';"
        val assets = createScanner().scanContent("app.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "OpenAI API" && it.type == AiAssetType.LLM_API })
    }

    @Test
    fun `detects TensorFlow`() {
        val code = "import tensorflow as tf; model = tf.keras.Sequential();"
        val assets = createScanner().scanContent("model.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "TensorFlow / Keras" && it.type == AiAssetType.ML_FRAMEWORK })
    }

    @Test
    fun `detects PyTorch`() {
        val code = "import torch; model = torch.nn.Module();"
        val assets = createScanner().scanContent("train.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "PyTorch" && it.type == AiAssetType.ML_FRAMEWORK })
    }

    @Test
    fun `detects HuggingFace Transformers`() {
        val code = "from transformers import AutoModel; model = AutoModel.from_pretrained('bert');"
        val assets = createScanner().scanContent("nlp.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "HuggingFace Transformers" })
    }

    @Test
    fun `detects LangChain`() {
        val code = "from langchain import LLMChain; chain = LLMChain();"
        val assets = createScanner().scanContent("app.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "LangChain" && it.type == AiAssetType.AI_ORCHESTRATION })
    }

    @Test
    fun `detects vector database`() {
        val code = "import chromadb; client = chromadb.Client();"
        val assets = createScanner().scanContent("rag.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.type == AiAssetType.VECTOR_DATABASE })
    }

    @Test
    fun `detects AI generated code marker`() {
        val code = "// This code was Generated by AI using GitHub Copilot"
        val assets = createScanner().scanContent("Utils.java", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.type == AiAssetType.AI_GENERATED_CODE })
    }

    @Test
    fun `detects MLOps platform`() {
        val code = "import mlflow; mlflow.start_run();"
        val assets = createScanner().scanContent("pipeline.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.type == AiAssetType.MLOPS })
    }

    @Test
    fun `returns empty for non-ai code`() {
        val code = "System.out.println(\"Hello World\");"
        val assets = createScanner().scanContent("Hello.java", code)
        assertTrue(assets.isEmpty())
    }

    @Test
    fun `detects ONNX`() {
        val code = "import onnxruntime as ort; session = ort.InferenceSession('model.onnx');"
        val assets = createScanner().scanContent("inference.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "ONNX Runtime" })
    }
}
