// Unit tests for AiScanner
package io.dyuti.osvplugin.aibom

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class AiScannerTest {
    private fun createScanner(): AiScanner = AiScanner(project = null)

    // ────────────────── POSITIVE DETECTION TESTS ──────────────────

    @Test
    fun `detects OpenAI API`() {
        val code = "import openai; openai.api_key = 'sk-test';"
        val assets = createScanner().scanContent("app.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "OpenAI API" && it.type == AiAssetType.LLM_API })
    }

    @Test
    fun `detects TensorFlow`() {
        val code = "import tensorflow as tf; model = tf.keras.Sequential();"
        val assets = createScanner().scanContent("model.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "TensorFlow / Keras" && it.type == AiAssetType.ML_FRAMEWORK })
    }

    @Test
    fun `detects PyTorch`() {
        val code = "import torch; model = torch.nn.Module();"
        val assets = createScanner().scanContent("train.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "PyTorch" && it.type == AiAssetType.ML_FRAMEWORK })
    }

    @Test
    fun `detects HuggingFace Transformers`() {
        val code = "from transformers import AutoModel; model = AutoModel.from_pretrained('bert');"
        val assets = createScanner().scanContent("nlp.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "HuggingFace Transformers" })
    }

    @Test
    fun `detects LangChain`() {
        val code = "from langchain import LLMChain; chain = LLMChain();"
        val assets = createScanner().scanContent("app.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "LangChain" && it.type == AiAssetType.AI_ORCHESTRATION })
    }

    @Test
    fun `detects vector database`() {
        val code = "import chromadb; client = chromadb.Client();"
        val assets = createScanner().scanContent("rag.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.type == AiAssetType.VECTOR_DATABASE })
    }

    @Test
    fun `detects AI generated code marker`() {
        val code = "// This code was Generated by AI using GitHub Copilot"
        val assets = createScanner().scanContent("Utils.java", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.type == AiAssetType.AI_GENERATED_CODE })
    }

    @Test
    fun `detects MLOps platform`() {
        val code = "import mlflow; mlflow.start_run();"
        val assets = createScanner().scanContent("pipeline.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.type == AiAssetType.MLOPS })
    }

    @Test
    fun `detects ONNX`() {
        val code = "import onnxruntime as ort; session = ort.InferenceSession('model.onnx');"
        val assets = createScanner().scanContent("inference.py", code)
        assertTrue(assets.isNotEmpty())
        assertTrue(assets.any { it.name == "ONNX Runtime" })
    }

    // ────────────────── FALSE POSITIVE TESTS ──────────────────

    @Test
    fun `no false positives on benign code`() {
        val benignLines =
            listOf(
                // .build() is common in Java builders — NOT OpenAI
                "val gson = GsonBuilder().setPrettyPrinting().create()",
                // Completion is an IntelliJ API — NOT OpenAI
                "class OsVCompletionContributor : CompletionContributor()",
                // @generated is a JAXB annotation — NOT AI
                "@Generated(value = \"org.example\")",
                // Transformers is a JetBrains XML API — NOT HuggingFace
                "val tf = javax.xml.transform.TransformerFactory.newInstance()",
                // tf prefix is common in variable names
                "var tf = Typeface.create(\"sans\", Typeface.NORMAL)",
                // predict/fit are common method names
                "val prediction = model.predict(input)",
                "model.fit(trainingData)",
                // Embedding in a generic class name
                "class MyEmbedding { fun encode() {} }",
                // ort is a common abbreviation
                "val ort = OrthogonalMatrix()",
                // onNext in reactive streams (partial onnx match)
                "stream.onNext { println(it) }",
                // Generic builder
                "val toolbar = JBToolbar().build()",
            )

        val failures = mutableListOf<String>()
        benignLines.forEach { line ->
            val assets = createScanner().scanContent("Test.java", line)
            if (assets.isNotEmpty()) {
                failures.add("\"$line\" -> ${assets.map { "${it.name}[${it.type}]" }}")
            }
        }
        assertTrue(
            failures.isEmpty(),
            "False positives detected:\n${failures.joinToString("\n")}",
        )
    }
}
